[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aiai_onchain_v1 = "7Br9YjPsgziRbUxmHxCxjq2fnBM17FzXo8XBwqbikXpi"

[programs.devnet]
aiai_onchain_v1 = "FDCr1ogj5pg5HVVKwoRoBkuvbPMk1Hvapk5efAh4j1JG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

